#!/usr/bin/env python3
"""``apps/sample_telemetry.json`` 레코드를 Postgres ER 테이블에 넣기.

- **권장:** DB URL 설정 후 이 스크립트 실행 → ``telemetry_db`` 와 동일 INSERT.
- **대안:** ``--emit-sql`` 로 DBeaver/psql용 ``.sql`` 파일만 생성.

사용::

    cd catena-x
    export COBOT_DATABASE_URL='postgresql://...'
    python3 scripts/seed_sample_telemetry.py

    python3 scripts/seed_sample_telemetry.py --emit-sql sql/seed_from_sample_telemetry.sql
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any, Dict, List

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

SAMPLE_PATH = ROOT / "apps" / "sample_telemetry.json"
EVENT_PREFIX = "sample-seed"
SCHEMA_VERSION = "1"
RECEIVED_AT = "2026-04-15T12:00:00Z"


def _load_records() -> List[Dict[str, Any]]:
    raw = json.loads(SAMPLE_PATH.read_text(encoding="utf-8"))
    if isinstance(raw, dict):
        return [raw]
    return list(raw)


def _checksum(payload: Dict[str, Any]) -> str:
    from apps.telemetry_db import checksum_payload_sha256

    return checksum_payload_sha256(payload)


def _payload_json_canonical(payload: Dict[str, Any]) -> str:
    return json.dumps(payload, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def _sql_str(s: str) -> str:
    return "'" + str(s).replace("'", "''") + "'"


def emit_sql(out_path: Path) -> None:
    from apps.telemetry_db import T_AUDIT, T_LATEST, T_MEAS, T_RAW, T_SYNC

    records = _load_records()
    lines: List[str] = [
        "-- Generated by scripts/seed_sample_telemetry.py --emit-sql",
        "-- 스키마: sql/postgres_cobot_telemetry.sql 적용 후 실행.",
        "-- 같은 시드 다시 넣으려면 아래 한 번 실행 후 이 파일 재실행:",
        "-- DELETE FROM cobot_telemetry_raw WHERE event_id LIKE 'sample-seed-%';",
        "",
        "BEGIN;",
        "",
    ]

    for i, rec in enumerate(records):
        idx = i + 1
        event_id = f"{EVENT_PREFIX}-{idx:02d}"
        chk = _checksum(rec)
        pj = _payload_json_canonical(rec)
        robot_id = str(rec["robot_id"])
        line_id = str(rec["line_id"])
        station_id = str(rec["station_id"])
        produced_at = str(rec.get("produced_at") or RECEIVED_AT)

        tag = f"p{idx:02d}"
        lines.append(f"INSERT INTO {T_RAW} (")
        lines.append(
            "    event_id, robot_id, line_id, station_id, produced_at, payload,"
            " schema_version, received_at, source_ip, content_type, request_id, checksum_sha256"
        )
        lines.append(") VALUES (")
        lines.append(f"    {_sql_str(event_id)},")
        lines.append(f"    {_sql_str(robot_id)},")
        lines.append(f"    {_sql_str(line_id)},")
        lines.append(f"    {_sql_str(station_id)},")
        lines.append(f"    {_sql_str(produced_at)}::timestamptz,")
        lines.append(f"    ${tag}${pj}${tag}$::jsonb,")
        lines.append(f"    {_sql_str(SCHEMA_VERSION)},")
        lines.append(f"    {_sql_str(RECEIVED_AT)}::timestamptz,")
        lines.append("    NULL,")
        lines.append("    'application/json',")
        lines.append("    'seed-script',")
        lines.append(f"    {_sql_str(chk)}")
        lines.append(");")
        lines.append("")

        temp = rec.get("temperature_c")
        vib = rec.get("vibration_mm_s")
        temp_sql = "NULL" if temp is None else str(float(temp))
        vib_sql = "NULL" if vib is None else str(float(vib))

        lines.append(f"INSERT INTO {T_MEAS} (")
        lines.append("    event_id, robot_id, line_id, station_id, produced_at,")
        lines.append("    cycle_time_ms, power_watts, program_name, status,")
        lines.append("    good_parts, reject_parts, temperature_c, vibration_mm_s")
        lines.append(") VALUES (")
        lines.append(f"    {_sql_str(event_id)},")
        lines.append(f"    {_sql_str(robot_id)},")
        lines.append(f"    {_sql_str(line_id)},")
        lines.append(f"    {_sql_str(station_id)},")
        lines.append(f"    {_sql_str(produced_at)}::timestamptz,")
        lines.append(f"    {float(rec['cycle_time_ms'])!r},")
        lines.append(f"    {float(rec['power_watts'])!r},")
        lines.append(f"    {_sql_str(str(rec['program_name']))},")
        lines.append(f"    {_sql_str(str(rec['status']))},")
        lines.append(f"    {int(rec.get('good_parts', 0))},")
        lines.append(f"    {int(rec.get('reject_parts', 0))},")
        lines.append(f"    {temp_sql},")
        lines.append(f"    {vib_sql}")
        lines.append(");")
        lines.append("")

        lines.append(f"INSERT INTO {T_LATEST} (robot_id, line_id, station_id, produced_at, payload, updated_at)")
        lines.append("VALUES (")
        lines.append(f"    {_sql_str(robot_id)},")
        lines.append(f"    {_sql_str(line_id)},")
        lines.append(f"    {_sql_str(station_id)},")
        lines.append(f"    {_sql_str(produced_at)}::timestamptz,")
        lines.append(f"    ${tag}${pj}${tag}$::jsonb,")
        lines.append(f"    {_sql_str(RECEIVED_AT)}::timestamptz")
        lines.append(")")
        lines.append("ON CONFLICT (robot_id) DO UPDATE SET")
        lines.append("    line_id = EXCLUDED.line_id,")
        lines.append("    station_id = EXCLUDED.station_id,")
        lines.append("    produced_at = EXCLUDED.produced_at,")
        lines.append("    payload = EXCLUDED.payload,")
        lines.append("    updated_at = EXCLUDED.updated_at;")
        lines.append("")

        lines.append(f"INSERT INTO {T_SYNC} (event_id, robot_id, sync_status, last_error, synced_at, retry_count, updated_at)")
        lines.append("VALUES (")
        lines.append(f"    {_sql_str(event_id)},")
        lines.append(f"    {_sql_str(robot_id)},")
        lines.append("    'Pending',")
        lines.append("    NULL,")
        lines.append("    NULL,")
        lines.append("    0,")
        lines.append(f"    {_sql_str(RECEIVED_AT)}::timestamptz")
        lines.append(");")
        lines.append("")

        det = json.dumps({"event_id": event_id, "robot_id": robot_id}, ensure_ascii=False)
        lines.append(f"INSERT INTO {T_AUDIT} (")
        lines.append(
            "    event_time, actor_type, actor_id, action, target_resource, result, correlation_id, details"
        )
        lines.append(") VALUES (")
        lines.append(f"    {_sql_str(RECEIVED_AT)}::timestamptz,")
        lines.append("    'Service',")
        lines.append("    'seed-script',")
        lines.append("    'Ingest',")
        lines.append(f"    {_sql_str('telemetry:' + robot_id)},")
        lines.append("    'Success',")
        lines.append("    'seed-script',")
        lines.append(f"    {_sql_str(det)}::jsonb")
        lines.append(");")
        lines.append("")

    lines.append("COMMIT;")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out_path} ({len(records)} robots)")


def ingest_via_python(dsn: str) -> None:
    from apps.telemetry_db import ingest_http_payload_postgres

    records = _load_records()
    for i, rec in enumerate(records):
        ingest_http_payload_postgres(
            dsn,
            rec,
            client_ip="127.0.0.1",
            request_id="seed-script",
            actor_id="seed-script",
            event_id=f"{EVENT_PREFIX}-{i + 1:02d}",
        )
        print(f"OK {i + 1}/{len(records)} {rec.get('robot_id')}")


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--emit-sql",
        metavar="FILE",
        help="DB 연결 없이 SQL 파일만 생성 (예: sql/seed_from_sample_telemetry.sql)",
    )
    args = p.parse_args()

    if args.emit_sql:
        emit_sql(Path(args.emit_sql))
        return

    dsn = os.environ.get("COBOT_DATABASE_URL", "").strip() or os.environ.get("DATABASE_URL", "").strip()
    if not dsn:
        print("COBOT_DATABASE_URL 또는 DATABASE_URL 을 설정하거나, --emit-sql 로 SQL만 만드세요.", file=sys.stderr)
        sys.exit(1)
    ingest_via_python(dsn)


if __name__ == "__main__":
    main()
